import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "coquette-duck",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="fuji">
      
      <body className={inter.className}>
        <div className="dark:bg-slate-800">
          {children}
        </div>
      </body>
      
    </html>
  );
}
