import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "I am a title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="fuji">
      
      <body className={inter.className}>
        <div className="dark:bg-[#FCFCFC] h-screen w-screen">
          {children}
          <Analytics />
        </div>
      </body>
      
    </html>
  );
}
